# EPIC Configuration for Host PC
# Optimized for performance with enhanced visualization capabilities

# Topic parameters - same as simulation
odometry_topic: /quad_0/lidar_slam/odom
cloud_topic: /quad0_pcl_render_node/cloud

# TSP solver configuration - Host PC path
exploration/tsp_dir: /home/wave/catkin_ws_host/src/EPIC/src/global_planner/utils/lkh_tsp_solver/resource

# Global planning weights
global_planning/w_vdir: 1.2
global_planning/w_yawdir: 0.0
global_planning/w_firstnode: 0.2

# Visualization - enabled for better debugging and monitoring on Host PC
view_graph: true
FrontierManager/view_cluster: true
FrontierManager/view_frt: true

# Graph parameters
bubble_topo/min_x: 0.6
bubble_topo/min_y: 0.6
bubble_topo/min_z: 0.3
bubble_topo/bubble_min_radius: 0.61
bubble_topo/init_region_size_x: 2.5
bubble_topo/init_region_size_y: 2.5
bubble_topo/init_region_size_z: 2.0
bubble_topo/cube_discrete_size: 0.25
bubble_topo/odom_node_distance: 3.0
bubble_astar/safe_distance: 0.6
bubble_astar/allocate_num: 100000  # Increased for Host PC memory capacity

# Map parameters
max_update_region_num: 99999999
frontier/candidate_dphi: 0.26
frontier/candidate_znum: 3

# LiDAR perception
lidar_perception/fov_up: 52.0
lidar_perception/fov_down: -7.0
lidar_perception/lidar_pitch: 40.0
lidar_perception/fov_viewpoint_up: 48.0
lidar_perception/fov_viewpoint_down: -5.0
lidar_perception/max_ray_length: 18

# Parallel processing - optimized for Host PC performance
parallel_astar/update_connection_timeout: 0.002  # Faster processing on Host PC
parallel_astar/insert_node_timeout: 0.002       # Faster processing on Host PC

# Frontier management
FrontierManager/cell_size: 0.4
FrontierManager/noise_cell_range: 1
FrontierManager/good_observation_direction_score: 0.8
FrontierManager/good_observation_force_trust_length: 4.0
FrontierManager/good_observation_trust_length: 12.0
FrontierManager/update_length: 15.0
FrontierManager/cluster_max_size: 7.5
FrontierManager/cluster_min_size: 2.0
FrontierManager/cluster_min_radius: 1.0
FrontierManager/cluster_direction_radius: 0.15
FrontierManager/cluster_minmum_point_num: 5

# Viewpoint sampling
ViewpointManager/sample_pillar_min_height: 1.0
ViewpointManager/sample_pillar_max_height: 3.5
ViewpointManager/sample_pillar_height_layer_num: 3
ViewpointManager/sample_pillar_min_radius: 1.5
ViewpointManager/sample_pillar_max_radius: 4.0
ViewpointManager/sample_pillar_radius_layer_num: 3
ViewpointManager/sample_pillar_circle_sample_num: 8
ViewpointManager/local_tsp_size: 20

# Exploration area
box_num: 1
box_0/down: [-100.0, -600.0, 0]
box_0/up: [182.0, 150.2, 3]
dead_area_num: 0

# Trajectory parameters - more aggressive for Host PC processing
max_traj_len: 10.0                   # Increased from ARM version (8.0)
DilateRadiusSoft: 0.6
DilateRadiusHard: 0.5
MaxCorridorSize: 3.5
MaxVelMag: 4.0                       # Increased from ARM version (2.5)
maxBdrMag: 10000.0                   # Increased from ARM version (8000.0)
MaxTiltAngle: 0.5
MinThrust: 15.0
MaxThrust: 22.0
VehicleMass: 1.9
GravAcc: 9.8
HorizDrag: 0.70
VertDrag: 0.80
ParasDrag: 0.01
SpeedEps: 0.0001
WeightT: 2000.0
WeightSafeT: 400.0

# Weight vector [pos_weight, vel_weight, omg_weight, theta_weight, thrust_weight]
ChiVec: [2.0e+5, 1.5e+4, 1.0e+4, 1.0e+5, 1.0e+5]
SmoothingEps: 0.015
IntegralIntervs: 32
RelCostTol: 1.0e-6

# Yaw optimization
yaw_max_vel: 4.0
yaw_rho_vis: 10000.0
yaw_time_fwd: 3.0 